---
title: "TidyTuesday 30 Jan 2024"
author: "COMP/STAT 112"
date: "2024-03-01"
output: html_document
---

# Groundhog predictions

Happy Groundhog Day! This week we're exploring Groundhog Day Predictions from [groundhog-day.com](https://groundhog-day.com)!
See if you can find a better way to present the annual data than their [table of predictions by year](https://groundhog-day.com/predictions)!
For anyone not familiar with the Groundhog Day tradition, if the groundhog sees its shadow and goes back into its burrow, that is a prediction of six more weeks of winter.
Otherwise spring will come early.
We attempted to provide weather data to accompany this dataset, but so far we've been unsuccessful.
Watch for a follow-up dataset in the future!

Note: "Oil Springs Ollie" (groundhog #55) has been succeeded by "Heaven's Wildlife Harvey" (groundhog #70).

## The Data

```{r,message=FALSE,warning=FALSE}

library(tidyverse)




groundhogs <- read_csv("https://raw.githubusercontent.com/djoloughlin/tidytuesday_1_30_2024/main/groundhogs")

predictions <- read_csv("https://raw.githubusercontent.com/djoloughlin/tidytuesday_1_30_2024/main/predictions")

str(groundhogs)

str(predictions)

```

## How to Participate

- [Explore the data](https://r4ds.hadley.nz/), watching out for interesting relationships. We would like to emphasize that you should not draw conclusions about **causation** in the data. There are various moderating variables that affect all data, many of which might not have been captured in these datasets. As such, our suggestion is to use the data provided to practice your data tidying and plotting techniques, and to consider for yourself what nuances might underlie these relationships.
- Create a visualization, a model, a [shiny app](https://shiny.posit.co/), or some other piece of data-science-related output, using R or another programming language.
- [Share your output and the code used to generate it](../../../sharing.md) on social media with the #TidyTuesday hashtag.